language: python

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt

  - pip install coveralls

env:
  - FLASK_VERSION=1.0.2

script:
  - python3 -m pytest --with-coverage --cover-package=app/api/v1 && coverage report
  - coveralls

after_success:
  - coveralls
